select * from customer limit 13

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(customer.purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer c
where discount_applied = 'Yes' and c.purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric), 1) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
ROUND(avg(purchase_amount::Numeric), 2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- Q6. Show top 5 products have total purchases & discounted purchases
SELECT
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 THEN 'New😑'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning🫡'
ELSE 'Loyal😊'
END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) as "number_of_customers"
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;





